require:
  - standard
  - rubocop-rspec
  - rubocop-performance

inherit_gem:
  standard: config/base.yml

AllCops:
  NewCops: enable

RSpec:
  Enabled: true

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: space

Layout/EmptyLineAfterMagicComment:
  Enabled: false
